### ISSUE TITLE
No mention of installing dependencies in README.md

### ISSUE THREAD

**Issue by scoliann** [hlin117/mdlp-discretization#10]
`README.md` only mentions `nose` dependency, and does not mention how to install dependencies in `requirements.txt` using `pip install -r requirements`.

Proposed solution:
1.  Add nose to `requirements.txt`
2.  Add documentation to `README.md` explaining to use `pip install -r requirements`

Thoughts?

**Comment by hlin117** [comment]
Traditionally, `requirements.txt` isn't supposed to contain any packages used for testing. On the other hand you can can have a `requirements-tests.txt` which contain these packages.

I wouldn't mind a PR from someone to add `pip install -r requirements` :)
