### ISSUE TITLE
More clean packaging

### ISSUE THREAD

**Issue by dodgejoel** [hlin117/mdlp-discretization#20]
Would be nice to enable more cleanly integrating this package into a larger project. e.g. making it easier to install this package into a virtualenv. See https://github.com/thearn/simple-cython-example for example.

**Comment by hlin117** [comment]
Thanks for the suggestion. Do you have any suggestions on what need to be done to let this library be integrated into larger libraries?

**Comment by dodgejoel** [comment]
see https://github.com/hlin117/mdlp-discretization/pull/22
