### ISSUE TITLE
Getting MDLP output as Empty array

### ISSUE THREAD

**Issue by manishbansal-fk** [hlin117/mdlp-discretization#6]
@hlin117 
I am using MDLP transformer to get discretize values of a continuous variable. But I am getting MDLP output as Empty array. Below are data attributes as

E.g. 
mdlp = MDLP()
mdlp.fit_transform(X.A.values.reshape(-1,1), yy)  # Here X is pandas dataframe
# Details :

X = 
count    1383730.000000
mean       5.899136
std           12.970693
min            1.000000
25%            1.000000
50%            3.000000
75%            6.000000
max          728.000000
**Name: A, dtype: float64**

yy = array([0, 0, 0, ..., 0, 0, 0])

xs.shape : (4708872, 1)
yy.shape : (4708872,)

Is Empty output a valid output ? Please suggest. 

Note : It is working for some of the features.

**Comment by hlin117** [comment]
It might be a dataset issue similar to #2. Have you tried changing the `min_depth` parameter?

PS: I think the function should work if `xs` is of shape `(4708872,)`.

**Comment by manishbansal-fk** [comment]
Thanks for pointing out min_depth parameter.

But how do we ensure that what is optimal value of min_depth for a feature.

**Comment by hlin117** [comment]
Technically, hard wiring the min_depth parameter is already against the
will of the original paper. The original paper argued for a heuristic for
when to stop cutting.

But if you wanted to move forward with this, min_depth is another
hyperparameter you can tune thru cross validation.

**Comment by manishbansal-fk** [comment]
Thanks a lot.

**Comment by hlin117** [comment]
Yes, good luck!
