### ISSUE TITLE
Compile errors with python 2.7

### ISSUE THREAD

**Issue by aclyde11** [hlin117/mdlp-discretization#8]
Hello,

I cannot seem to figure out how to get this code to compile using python 2.7. Whenever I use python 3 it complies fine but when I use python 2.7 (no matter what computer I'm on), I get an error along the lines of 
<utility.h> is not found.

**Comment by hlin117** [comment]
Did you try using a virtual environment? There's a `requirements.txt` I provided which should get you started.

What OS are you using?

**Comment by hlin117** [comment]
I'm going to close this issue unless you're still experiencing troubles.
